language: go
go:
- 1.6
sudo: false
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ./setup-version.sh
script:
- make release
env:
  global:
    secure: bL1vIp85qaaHEjjcVx9nJKFMtOPwBO2fxMs6wO8qrr1RgLfOm4NrKSyeki4FOZKXdA5+rIRFiszev3zrKm1/neeKXrYV0ExXyoMCBjlvHiUiI6xmmslp1YT9nEvoFrKupCB/nG8v+L3IYpSNuSdVyoPkTe7l5ISaMHIrrqSkEO+bEp4eWOwtjAeBGRH61uZ05wp9OG/3eG5Z5QmWBNsmrhL3EOyvyT52+ugJ/9dev9eNYh7WX2fwwcRkwYOhRI2qbysgi7Ou6aYdidb0Bs1YxqqWdI+necw20Xqau36iStH8HR+0t8iQxr9BX8QfCLZCH+NmTZp29njkPyC2quJ40yYaPht6KtVA5bQb5STIlQyhGvjUZKA1MbnKm6MTNW8YsX8ZAh7V/2ie+0LfewDRyaf5+SQmdPTEsIjrqHsE+r96B7KanH979spq70Z36XG+aMwUaDV+cH7YfdX1Cg58A3kfR4JDFmN6B1fFfiTMeVBcGe8t76VLNy7uVhV0PAsZfU+ItymeGHVf0RgKVJFCYk0IoyA1WTRUI7Hzk7aOo3Qd2KgfiQz3THlQ2TAi/Aj92pKU2xvArzy2X5upI0+Y+3NYxKiz+Tz3OkH3f48OUa7xiKgMqivnTPm2qNT2NWKRlIlyTRVr2K0Mx07rcWxxvYNEGJJKtAVlYE7cskakp64=
