---
name: Build and Test
"on":
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    branches:
      - "*"
  workflow_call:
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check style
        run: go run mage.go style

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Lint
        run: go run mage.go lint
      - name: Publish Linter Reports
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '.junit/*.xml'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test
        run: go run mage.go test
      - name: Merge Coverage Files
        run: go run mage.go coverage
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: .cover.out

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go run mage.go binary

#  deploy:
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Setup Go
#        uses: actions/setup-go@v2
#      - name: Build Release
#        run: make -j$(cat /proc/cpuinfo | grep processor | wc -l) release
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/r')
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          files: |
#            callback-linux-arm.tar.gz
#            callback-linux-arm64.tar.gz
#            callback-linux-x86_64.tar.gz
#            callback-linux-i386.tar.gz
#            callback-windows-i386.zip
#            callback-windows-x86_64.zip
#            callback-darwin-x86_64.tar.gz
#            callback-darwin-arm64.tar.gz
#            callback-freebsd-x86_64.tar.gz